# Generated by Django 5.0.2 on 2024-03-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparklabs', '0002_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
