# Generated by Django 5.0.2 on 2024-03-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparklabs', '0004_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
