# Generated by Django 5.0.2 on 2024-03-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparklabs', '0004_project'),
        ('sparklabs', '0006_alter_project_project_image'),
    ]

    operations = [
    ]
