# Generated by Django 5.0.2 on 2024-03-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparklabs', '0007_merge_0004_project_0006_alter_project_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(upload_to='static/projects/images'),
        ),
    ]
